name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install Dependencies
        run: |
          cd backend
          go mod download
          
      - name: Run Tests
        run: |
          cd backend
          go test ./...
          
      - name: Build
        run: |
          cd backend
          go build ./cmd/server